# Generated by Django 4.0.4 on 2022-05-03 10:57

from django.db import migrations, models
import pl_user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pl_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=pl_user.utils.avatar_path),
        ),
    ]
