name: Django Tests CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10']

    steps:
      - uses: actions/checkout@v3
      # this fixes local act bug of python setup
      - name: local act python setup fix
        run: |
          # Hack to get setup-python to work on act
          # (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          cd back-end/
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: |
            cd back-end
            python manage.py migrate
      - name: Run Tests
        run: |
          cd back-end/
          python manage.py test apps/
      - name: Generate Report
        run: |
          pip install coverage
          cd back-end
          coverage run --source='.' manage.py test apps/
          coverage xml
          coverage report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
         fail_ci_if_error: true
         token: ${{ secrets.CODECOV_TOKEN }} 
         
